[package]
name = "rustsweeper"
version = "0.1.0"
authors = ["ieinberg <ieinberg@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
dialoguer = "0.7.1"
rand = "*"